### ISSUE TITLE
优化结局处理

### ISSUE THREAD

**Issue by serotoninphobe** [SerotoninPharmaceuticals/LD36#1]
因为计时在机器界面并不停止，所以现在的方式会让玩家在操作过程中莫名其妙就末日了。建议改为在最后1小时的时候，镜头切换到跟title screen一样的特写视角，让玩家见证最后一小时，然后才是黑屏。

**Comment by ouabing** [comment]
会不会需要一点强调时钟的画面效果？不然干看着整个画面似乎也有点呆

**Comment by serotoninphobe** [comment]
@ouabing 半小时换成真实时间也就5s，倒是挺短的。这样如何，最后1小时（10s）的时候时钟画面整体全屏淡入，玩家操作继续，到最后半小时（5s）的时候淡入完成，禁用玩家输入？

**Comment by ouabing** [comment]
感觉可以更怪一些？最后 1 小时的时候，画面变成另一种？比如突然画面只剩下那些架子上还没来得及埋葬的物品？

**Comment by serotoninphobe** [comment]
@ouabing 这想法不错！但是问题是要给特写的话，特写区域全部得重画放大版，而且特写的画风还不好统一，怕是时间来不及.... 最后环节的重点主要还是要交代时间的结束，这样子如何，不知道实现难度大不大。就是最后几分钟（游戏时间，也就是现实的最后1-2s的样子）的时候，用几个超快速剪辑交代下还没来得及埋葬的物品，每分钟之间插进去一个物品的特写画面，而且因为速度比较快，直接用放大的主界面画面就行。（但是感觉调试工作量还是很大....)

**Comment by ouabing** [comment]
超快速剪辑是什么意思？

**Comment by serotoninphobe** [comment]
@ouabing 就是每副画面只有几帧的速度，比如时间显示00:08-00：07之间（真实时间1/6秒）插进去一个特写画面这样
